# Generated by Django 3.0.3 on 2023-09-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0002_auto_20230915_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorders',
            name='total_price',
        ),
        migrations.AddField(
            model_name='customerorders',
            name='totalAmounts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
