# Generated by Django 3.0.3 on 2023-09-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0004_customerorders_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorders',
            name='totalAmount',
        ),
    ]
