# Generated by Django 3.0.3 on 2023-09-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0005_remove_customerorders_totalamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
