# Generated by Django 3.0.3 on 2023-09-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0006_dynamictext'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
