# Generated by Django 3.0.3 on 2023-09-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0011_auto_20230916_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
