# Generated by Django 3.0.3 on 2023-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0012_auto_20230916_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='quittung',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
