# Generated by Django 3.0.3 on 2023-09-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0015_auto_20230917_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retoure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sultanerp.Store')),
                ('products', models.ManyToManyField(to='sultanerp.InternalProducts')),
            ],
        ),
    ]
