# Generated by Django 3.0.3 on 2023-09-17 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0018_auto_20230918_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tortenbestellungsid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
