# Generated by Django 3.0.3 on 2023-09-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0020_wiki_wikicategory_wikicontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=50, null=True)),
                ('image_alt_title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wiki',
            name='images_reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sultanerp.WikiImages'),
            preserve_default=False,
        ),
    ]
