# Generated by Django 3.0.3 on 2023-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0021_auto_20230919_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikiimages',
            name='image_url',
        ),
        migrations.AddField(
            model_name='wikiimages',
            name='image',
            field=models.ImageField(default=1, upload_to='wiki/images/'),
            preserve_default=False,
        ),
    ]
