# Generated by Django 3.0.3 on 2023-09-19 14:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0022_auto_20230919_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiimages',
            name='image_resized',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format=None, keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='wiki/images/'),
            preserve_default=False,
        ),
    ]
