# Generated by Django 3.0.3 on 2023-09-19 14:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0023_wikiimages_image_resized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki/images/'),
        ),
        migrations.AlterField(
            model_name='wikiimages',
            name='image_resized',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='wiki/images/'),
        ),
    ]
