# Generated by Django 3.0.3 on 2023-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0024_auto_20230919_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='content_reference',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='images_reference',
        ),
        migrations.AddField(
            model_name='wiki',
            name='categories',
            field=models.ManyToManyField(to='sultanerp.WikiCategory'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='contents',
            field=models.ManyToManyField(to='sultanerp.WikiContent'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='images',
            field=models.ManyToManyField(to='sultanerp.WikiImages'),
        ),
    ]
