# Generated by Django 3.0.3 on 2023-09-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0026_externallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallinks',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sultanerp.Roles'),
        ),
    ]
