# Generated by Django 3.0.3 on 2023-09-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0027_auto_20230919_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='hierarchy',
            field=models.IntegerField(default=0),
        ),
    ]
