# Generated by Django 3.0.3 on 2023-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0028_roles_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='hierarchy',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
