# Generated by Django 3.0.3 on 2023-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0029_auto_20230919_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['hierarchy']},
        ),
        migrations.AddField(
            model_name='externallinks',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
