# Generated by Django 3.0.3 on 2023-09-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0030_auto_20230919_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictext',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
