# Generated by Django 3.0.3 on 2023-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0031_auto_20230919_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictext',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
