# Generated by Django 3.0.3 on 2023-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0033_auto_20230919_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='categories',
            field=models.ManyToManyField(blank=True, to='sultanerp.WikiCategory'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='contents',
            field=models.ManyToManyField(blank=True, to='sultanerp.WikiContent'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='images',
            field=models.ManyToManyField(blank=True, to='sultanerp.WikiImages'),
        ),
    ]
