# Generated by Django 3.0.3 on 2023-09-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0034_auto_20230919_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='deposit',
        ),
        migrations.AddField(
            model_name='deposit',
            name='paid_back',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='paid_back_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='sultanerp.DepositObject'),
            preserve_default=False,
        ),
    ]
