# Generated by Django 3.0.3 on 2023-09-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0035_auto_20230920_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='deposit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sultanerp.Store'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='customer_tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositobject',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
