# Generated by Django 3.0.3 on 2023-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0037_deposit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorders',
            name='delivery_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
