# Generated by Django 3.0.3 on 2023-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0039_auto_20230920_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='tortenbestellungsid',
            name='ordertype',
            field=models.CharField(default='Goethestr.30', max_length=50),
            preserve_default=False,
        ),
    ]
