# Generated by Django 3.0.3 on 2023-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0040_tortenbestellungsid_ordertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortenbestellungsid',
            name='ordertype',
            field=models.CharField(max_length=30),
        ),
    ]
