# Generated by Django 3.0.3 on 2023-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0041_auto_20230923_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
