# Generated by Django 3.0.3 on 2023-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sultanerp', '0042_admintools'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='internalproducts',
            name='category',
            field=models.CharField(blank=True, choices=[('Teigwaren', 'Teigwaren'), ('Baklava', 'Baklava'), ('Konditorei', 'Konditorei'), ('Backstube', 'Backstube'), ('Snacks', 'Snacks'), ('Restaurant', 'Restaurant'), ('Nachspeisen', 'Nachspeisen')], max_length=255),
        ),
    ]
